6. Определите функцию, переводящую список чисел в список соответствующих им названий.
(defun changeNumbersToString (listNumber &optional listString )
      ((lambda (number tail) 
        (cond 
          ((eq 1 number)  (changeNumbersToString  tail (cons "one" listString)))
          ((eq 2 number)  (changeNumbersToString  tail (cons "two" listString)))
          ((eq 3 number)  (changeNumbersToString  tail (cons "three" listString)))
          ((eq 4 number)  (changeNumbersToString  tail (cons "four" listString)))
          ((eq 5 number)  (changeNumbersToString  tail (cons "five" listString)))
          ((eq 6 number)  (changeNumbersToString  tail (cons "six" listString)))
          ((eq 7 number)  (changeNumbersToString  tail (cons "seven" listString)))
          ((eq 8 number)  (changeNumbersToString  tail (cons "eight" listString)))
          ((eq 9 number)  (changeNumbersToString  tail (cons "nine" listString)))
          ((eq 0 number)  (changeNumbersToString  tail (cons "zero" listString)))
          (t  listString)
         )
       )
        (car listNumber)
        (cdr listNumber)
      )
)
(print(changeNumbersToString '(1 2 3 4 5 0 9 8 7 6 ))) ; => ("six" "seven" "eight" "nine" "zero" "five" "four" "three" "two" "one") 
