6. Определите функцию, переводящую список чисел в список соответствующих им названий.
(defun changeNumbersToString (listNumber &optional listString )
      ((lambda (number tail) 
        (cond 
          ((eq 1 number)  (cons "one" (changeNumbersToString  tail listString)))
          ((eq 2 number)  (cons "two" (changeNumbersToString  tail listString)))
          ((eq 3 number)  (cons "three" (changeNumbersToString  tail listString)))
          ((eq 4 number)  (cons "four" (changeNumbersToString  tail listString)))
          ((eq 5 number)  (cons "five" (changeNumbersToString  tail listString)))
          ((eq 6 number)  (cons "six" (changeNumbersToString  tail listString)))
          ((eq 7 number)  (cons "seven" (changeNumbersToString  tail listString)))
          ((eq 8 number)  (cons "eight" (changeNumbersToString  tail  listString)))
          ((eq 9 number)  (cons "nine" (changeNumbersToString  tail  listString)))
          ((eq 0 number)  (cons "zero" (changeNumbersToString  tail  listString)))
          (t  listString)
         )
       )
        (car listNumber)
        (cdr listNumber)
      )
)
(print(changeNumbersToString '(1 2 3 4 5 0 9 8 7 6 ))) => ("one" "two" "three" "four" "five" "zero" "nine" "eight" "seven" "six") 
